language: node_js
node_js:
      - "8.9.3"
branches:
   only:
      - master

before_script:
  - npm install -g firebase-tools

script:
  - echo " deploying "

after_success:
   - firebase deploy --token $FIREBASE_TOKEN